# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for more information:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
# https://containers.dev/guide/dependabot

version: 2
updates:
  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: weekly

  - package-ecosystem: "docker"
    directories:
      - "docker"
      - "frontend
      - "backend"
      - "diplomarbeit"
      - "docker/nginx"
    schedule:
      interval: weekly

  - package-ecosystem: "npm"
    directory: "/frontend/"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/diplomarbeit/"
    schedule:
      interval: "daily"

  - package-ecosystem: "composer"
    directory: "/backend/"
    schedule:
      interval: "daily"
