name: Frontend Code Quality checks
on:
  push:
    branches: ["main"]
  pull_request:
    branches: [main]
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  prettier:
    name: Prettier
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm clean-install --include=dev
        working-directory: ./frontend

      - name: Check formatting with Prettier
        run: npm run check
        working-directory: ./frontend
